greenbone/docs

src/architecture.rst
**What**:
Added some content to architecture chapter. Based on: https://community.greenbone.net/t/about-gvm-20-08-and-21-04-architecture/8449
**Why**:
**How**:
**Checklist**:
=> Added some content to architecture.src

src/_static/custom.css
**What**:
Width of body div was increased. 
**Why**:
Text parts were a bit too narrow and code sections were cut off.
**How**:
**Checklist**:
=> Increased width of body div

src/architecture.rst, src/background.rst, src/history.rst, src/index.rst
**What**:
Rearrange architecture and history chapters into a background chapter. Added the history of openvas from openvas.org too.
Still not perfect because now background contains the architecture and the history at one html page. Not sure how to do this best with rst (toc and content).
**Why**:
**How**:
**Checklist**:
=> Add Background Chapter

src/architecture.rst, src/common/admin-user.rst, src/common/directory-permissions.rst, src/common/feed-import-owner.rst, src/common/gsa/description.rst, src/common/gsa/download.rst, src/common/gvm-libs/description.rst, src/common/gvm-libs/download.rst, src/common/gvmd/description.rst, src/common/gvmd/download.rst, src/common/initial-feed-sync.rst, src/common/introduction.rst, src/common/openvas-scanner/description.rst, src/common/openvas-scanner/download.rst, src/common/openvas-smb.rst, src/common/postgres.rst, src/common/prerequisites.rst, src/common/redis.rst, src/common/sudo-scanning.rst, src/common/systemd.rst, src/glossary.rst, src/gvm-20.08/index.rst, src/gvm-21.04/index.rst, src/gvm-21.04/ospd-openvas/download.rst, src/history.rst, src/index.rst
**What**:
- Fixed some spelling issues
- Unified formulations
**Why**:
**How**:
**Checklist**:
=> Fixed some spelling issues and unified texts

src/common/admin-user.rst, src/common/directory-permissions.rst, src/common/gvm-tools/dependencies.rst, src/common/gvm-tools/description.rst, src/common/gvm-tools/install.rst, src/common/postgres.rst, src/common/prerequisites.rst, src/gvm-20.08/index.rst, src/gvm-21.04/index.rst
**What**:
**Why**:
**How**:
**Checklist**:
=> Finalize docs

src/common/gsa/build.rst, src/common/gvm-libs/build.rst, src/common/gvmd/build.rst, src/common/openvas-scanner/build.rst, src/common/openvas-smb.rst
**What**:
* With `nproc` you can get the maximum threads possible for your CPU
**Why**:
**How**:
**Checklist**:
=> Use nproc to find max possible threads instead of fix 6

.github/CODEOWNERS
**What**:
**Why**:
**How**:
**Checklist**:
=> Add DevOps to codeowners for several files.

.github/workflows/github-pages.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Give the deploy workflow a name.

.github/CODEOWNERS
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix careless mistakes of owners.

.github/workflows/ci.yaml
**What**:
**Why**:
**How**:
**Checklist**:
=> Give the Workflow a name.

src/faq.md
**What**:
The status of GOS 20.08 was changed to "end-of-life".
**Why**:
Status of GOS 20.08 changed.
=> Updated GOS 20.08 status

test-build-and-install.sh, test-env.sh, test-setup.sh
**What**:
Add bash scripts for trying out most of the commands from the docs. The
files need to be updated allong with the docs. They can be run within a
docker container for quick testing
`docker run -it --rm --name test-docs debian:stable-slim /bin/bash`
`docker cp test-build-and-install.sh test-docs:/tmp`
`docker cp test-env.sh test-docs:/tmp`
`docker cp test-setup.sh test-docs:/tmp`
**Why**:
**How**:
**Checklist**:
=> Add scripts for testing the docs

src/common/sudo-scanning.rst
**What**:
Fixed a typo in a warning box
=> Fixed a typo

.github/workflows/deployment.yml, .github/workflows/github-pages.yml
**What**:
Extract the actual deployment to the gh-pages branch into a separate
reusable workflow and deploy the build sphinx doc to a lastest sub
directory.
**Why**:
Using a separate workflow will allow to deploy pull requests to
gh-pages for testing and viewing the changes in future too.
**How**:
**Checklist**:
=> Rework deployment for gh-pages

.github/workflows/ci.yaml, .github/workflows/cleanup-ci.yml, .github/workflows/deployment.yml, .github/workflows/github-pages.yml
**What**:
Deploy preview of PRs on gh-pages
**Why**:
Allow to view the preview of the changes in a pull request.
**How**:
**Checklist**:
=> Deploy preview of PRs on gh-pages

.github/dependabot.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Update GitHub actions via dependabot too

src/21.04/container/index.md
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: 404 Link, due to dir structure changes

src/_static/docker-compose.yml
additional we need the volume of openvas also in gvmd
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix gvmd with openvas-scanner greenbone-nvt-sync

src/21.04/container/index.md
**What**:
Move the advises on howto update the community containers, start from
scratch and to get a terminal into an own section: workflows.
**Why**:
**How**:
**Checklist**:
=> Split workflows from troubleshooting

poetry.lock, pyproject.toml
**What**:
Sphinx got a new major release.
**Why**:
**How**:
**Checklist**:
=> Update sphinx to 5.0.1

src/21.04/container/index.md
**What**:
These errors can be ignored but might confuse some users.
**Why**:
**How**:
**Checklist**:
=> Add troubleshooting for pg-gvm errors in logs

src/21.04/container/index.md, src/_static/setup-and-start-greenbone-community-edition.sh
**What**:
Add a shell script for running the containers
This is a very simple and basic script that setups and starts
containers. It may fail syncing the feed when something takes longer or
goes wrong.
**Why**:
We can provide a "try out this thing" one shot to test our software
**How**:
**Checklist**:
=> Add a shell script for running the containers

src/architecture.rst, src/history.rst, src/index.rst
**What**:
Fixed some typos in the introduction/history part
=> Fixed some typos in the introduction part

src/22.4/source-build/gsa/dependencies.rst, src/22.4/source-build/systemd.rst, src/changelog.md, src/common/source-build/openvas-smb.rst, src/common/source-build/redis.rst
**What**:
Fix issue with installing yarn and improve copy and paste with the sphinx-copybutton extension.
**Why**:
Building GSA was broken and now it's easier to copy and paste the commands
**How**:
**Checklist**:
=> Improve source build

src/common/source-build/introduction.rst
**What**:
Add explicit information what debian version is required.
**Why**:
to reduce confusion at the customers
**How**:
**Checklist**:
=> Change: Be more specific what debian version should be used for what source build.

src/22.4/source-build/gsa/dependencies.rst, src/22.4/source-build/gvm-libs/dependencies.rst, src/22.4/source-build/gvmd/dependencies.rst, src/22.4/source-build/mqtt-broker.rst, src/22.4/source-build/notus-scanner/dependencies.rst, src/22.4/source-build/openvas-scanner/dependencies.rst, src/22.4/source-build/ospd-openvas/dependencies.rst, src/22.4/source-build/pg-gvm/dependencies.rst, src/22.4/source-build/postgres.rst, src/common/source-build/gsad/dependencies.rst, src/common/source-build/gvm-tools/dependencies.rst, src/common/source-build/gvmd/build.rst, src/common/source-build/openvas-smb.rst, src/common/source-build/prerequisites.rst, src/common/source-build/redis.rst
**What**:
Init Fedora support for source install.
**Why**:
**How**:
**Checklist**:
=> Add: Init Fedora support

src/21.4/source-build/gsa/build.rst, src/21.4/source-build/gsa/dependencies.rst, src/22.4/source-build/gsa/dependencies.rst, src/changelog.md, src/common/source-build/introduction.rst
**What**:
Change: Adjust additional Debian specials now we support Fedora too
Also mention fedora in the supported distros and add a changelog entry.
**Why**:
**How**:
**Checklist**:
=> Change: Adjust additional Debian specials now we support Fedora too

src/21.4/source-build/gsa/build.rst, src/21.4/source-build/gsa/dependencies.rst, src/21.4/source-build/gvm-libs/dependencies.rst, src/21.4/source-build/gvmd/dependencies.rst, src/21.4/source-build/openvas-scanner/dependencies.rst, src/21.4/source-build/ospd-openvas/dependencies.rst, src/21.4/source-build/postgres.rst, src/common/source-build/gvmd/build.rst
**What**:
Add building 21.4 from Source on Fedora
**Why**:
**How**:
**Checklist**:
=> Add: Building 21.4 from Source on Fedora

src/common/container/preamble.md, src/common/container/prerequisites.md
**What**:
Add container setup for fedora.
**Why**:
**How**:
**Checklist**:
=> Add: container setup for fedora

src/faq.md
**What**:
**Why**:
**How**:
**Checklist**:
=> Change: Use correct GOS version (with the leading zero)

src/index.rst
There are only two supported versions.
**What**:
**Why**:
**How**:
**Checklist**:
=> Change: Put the supported versions into flowing text

src/21.4/source-build/gsa/build.rst, src/21.4/source-build/gsa/dependencies.rst, src/21.4/source-build/gvm-libs/dependencies.rst, src/21.4/source-build/gvmd/dependencies.rst, src/21.4/source-build/openvas-scanner/dependencies.rst, src/21.4/source-build/ospd-openvas/dependencies.rst, src/21.4/source-build/postgres.rst, src/21.4/source-build/systemd.rst, src/22.4/source-build/gsa/dependencies.rst, src/22.4/source-build/gvm-libs/dependencies.rst, src/22.4/source-build/gvmd/dependencies.rst, src/22.4/source-build/mqtt-broker.rst, src/22.4/source-build/notus-scanner/dependencies.rst, src/22.4/source-build/openvas-scanner/dependencies.rst, src/22.4/source-build/ospd-openvas/dependencies.rst, src/22.4/source-build/pg-gvm/dependencies.rst, src/22.4/source-build/postgres.rst, src/22.4/source-build/systemd.rst, src/common/container/preamble.md, src/common/container/prerequisites.md, src/common/source-build/gsad/dependencies.rst, src/common/source-build/gvm-tools/dependencies.rst, src/common/source-build/gvmd/build.rst, src/common/source-build/initial-feed-sync.rst, src/common/source-build/introduction.rst, src/common/source-build/openvas-smb.rst, src/common/source-build/prerequisites.rst, src/common/source-build/redis.rst, src/common/source-build/sudo-scanning.rst
**What**:
Add Centos support
**Why**:
**How**:
**Checklist**:
=> Add: Init Centos

src/21.4/source-build/gsa/build.rst, src/21.4/source-build/gsa/dependencies.rst, src/21.4/source-build/gvm-libs/dependencies.rst, src/21.4/source-build/gvmd/dependencies.rst, src/21.4/source-build/openvas-scanner/dependencies.rst, src/21.4/source-build/ospd-openvas/dependencies.rst, src/21.4/source-build/postgres.rst, src/22.4/source-build/gsa/dependencies.rst, src/22.4/source-build/gvm-libs/dependencies.rst, src/22.4/source-build/gvmd/dependencies.rst, src/22.4/source-build/mqtt-broker.rst, src/22.4/source-build/notus-scanner/dependencies.rst, src/22.4/source-build/openvas-scanner/dependencies.rst, src/22.4/source-build/ospd-openvas/dependencies.rst, src/22.4/source-build/pg-gvm/build.rst, src/22.4/source-build/pg-gvm/dependencies.rst, src/22.4/source-build/postgres.rst, src/changelog.md, src/common/container/preamble.md, src/common/container/prerequisites.md, src/common/source-build/gsad/dependencies.rst, src/common/source-build/gvm-tools/dependencies.rst, src/common/source-build/gvmd/build.rst, src/common/source-build/introduction.rst, src/common/source-build/openvas-smb.rst, src/common/source-build/prerequisites.rst, src/common/source-build/redis.rst, src/common/source-build/sudo-scanning.rst
**What**:
Init ubuntu support
**Why**:
**How**:
**Checklist**:
=> Add: Init ubuntu

src/common/container/preamble.md, src/common/source-build/introduction.rst
**What**:
Add Hardware requirements for container and source build setup.
**Why**:
**How**:
**Checklist**:
=> Add: Hardware requirements

src/api.md, src/changelog.md, src/index.rst
**What**:
Add: Add a new API page for links to our other community docs
**Why**:
**How**:
**Checklist**:
=> Add: Add a new API page for links to our other community docs

src/21.4/container/index.md, src/21.4/source-build/index.rst, src/22.4/container/index.md, src/22.4/source-build/index.rst, src/common/container/hardware.md, src/common/container/preamble.md, src/common/source-build/hardware.rst, src/common/source-build/introduction.rst
**What**:
Fix displaying the heading level of the prerequisites and hardware
requirements by moving the hardware requirements into separate files and
after the introduction into the docs.
**Why**:
**How**:
**Checklist**:
=> Change: Extract hardware requirements into own documents

src/21.4/source-build/index.rst, src/22.4/container/index.md, src/22.4/source-build/index.rst, src/22.4/source-build/notus-scanner/description.rst, src/architecture.rst, src/common/source-build/gvm-tools/description.rst, src/common/source-build/gvmd/description.rst, src/common/source-build/initial-feed-sync.rst, src/common/source-build/introduction.rst, src/common/source-build/openvas-smb.rst, src/common/source-build/ospd-openvas/description.rst, src/common/source-build/prerequisites.rst, src/glossary.rst, src/history.rst, src/index.rst
**What**:
* Check all content for our current terms from the naming schema
* Update chapters for additional information
* Add additional links
**Why**:
Mostly to use Greenbone Community Edition wherever possible.
**How**:
**Checklist**:
=> Improve docs

src/common/container/workflows.md
**What**:
Improved wording of https://github.com/greenbone/docs/pull/163
=> Fixed wording of gvmd Unix socket section

src/_static/custom.css
**What**:
Updated some CSS settings for links in the left sidebar
=> Updated some CSS settings for links in the left sidebar

src/21.4/container/index.md, src/22.4/container/index.md
**What**:
Add a hint about following the prerequisites
DEVOPS-373
**Why**:
For running the script it is required to follow the prerequisites first.
Without following the prerequisites the script wont work at all.
**How**:
**Checklist**:
=> Change: Add a hint about following the prerequisites

src/21.4/container/index.md, src/22.4/container/index.md, src/changelog.md
**What**:
Download setup script into current working directory
DEVOPS-373
**Why**:
Avoid that users who don't follow the guide step by step don't have a
DOWNLOAD_DIR created fail with downloading the script.
**How**:
**Checklist**:
=> Change: Download setup script into current working directory

src/_static/setup-and-start-greenbone-community-edition.sh, src/changelog.md
**What**:
**Why**:
**How**:
**Checklist**:
=> Fixes for DEVOPS-374

src/_static/setup-and-start-greenbone-community-edition.sh, src/changelog.md
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: Fixing the checks for required programs

poetry.lock, pyproject.toml, src/changelog.md, src/conf.py, src/index.rst
**What**:
Add meta information to generated HTML documents
**Why**:
Better preview in links at social media sites and also better influence in search engine ranking
**How**:
**Checklist**:
=> HTML meta information

.github/workflows/deployment.yml, src/21.4/source-build/gsa/build.rst, src/22.4/source-build/gsa/build.rst, src/22.4/source-build/notus-scanner/build.rst, src/22.4/source-build/pg-gvm/build.rst, src/changelog.md, src/common/source-build/gsad/build.rst, src/common/source-build/gvm-libs/build.rst, src/common/source-build/gvm-tools/install.rst, src/common/source-build/gvmd/build.rst, src/common/source-build/openvas-scanner/build.rst, src/common/source-build/openvas-smb.rst, src/common/source-build/ospd-openvas/build.rst, test-build-and-install.sh
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix: Improve documentation

src/21.4/source-build/index.rst, src/21.4/source-build/troubleshooting.md, src/22.4/source-build/index.rst, src/22.4/source-build/troubleshooting.md, src/common/container/troubleshooting.md, src/common/source-build/troubleshooting.md, src/faq.md
**What**:
Extend troubleshooting guides
**Why**:
We should add as much common issues and their solutions as possible to avoid unnecessary issues for our community users.
**How**:
**Checklist**:
=> Extend troubleshooting

src/changelog.md
**What**:
Fix typo in variable name within changelog.md
**Why**:
N/A
**How**:
N/A
=> Fix typo in variable name within changelog.md

src/glossary.rst
**What**:
Describe the term feed in the glossary>
The term feed is mentioned at several places in the docs. 
**Why**:
Allow to link this term to its explanation in the glossary for the future.
**How**:
**Checklist**:
=> Add: Describe the term feed in the glossary

Makefile, poetry.lock, pyproject.toml
**What**:
Allow to rebuild the docs automatically aka. livehtml
Add sphinx-autobuild to provide a livereload http server for the html docs.
**Why**:
Easier development of the docs.
=> Add: Allow to rebuild the docs automatically aka. livehtml

src/changelog.md, src/common/source-build/troubleshooting.md
**What**:
Add more topics for the troubleshooting section of the build from source guide.
**Why**:
Give more hints about possible solutions for common issues.
=> Add: Extend troubleshooting for source build

src/22.4/source-build/index.rst, src/22.4/source-build/pg-gvm/version.rst, src/changelog.md
**What**:
Update components to 22.4.1 release
DEVOPS-493
**Why**:
We got new bugfix releases of our software components.
=> Change: Update components to 22.4.1 release

src/22.4/source-build/index.rst, src/changelog.md
A new ospd-openvas release was published.
=> Change: Use latest release of ospd-openvas

src/22.4/source-build/gsa/build.rst, src/22.4/source-build/gsad/build.rst, src/22.4/source-build/gvm-libs/build.rst, src/22.4/source-build/gvm-tools/install.rst, src/22.4/source-build/gvmd/build.rst, src/22.4/source-build/notus-scanner/build.rst, src/22.4/source-build/openvas-scanner/build.rst, src/22.4/source-build/openvas-smb.rst, src/22.4/source-build/ospd-openvas/build.rst, src/22.4/source-build/pg-gvm/build.rst, src/changelog.md
Install all components into dedicated install directory
Don't pollute a single installation directory and separate the to be installed files of each component.
=> Improve installation

.github/workflows/ci.yaml, .github/workflows/github-pages.yml
Run workflows with poetry 1.4.0
Installing the furo theme is broken with poetry 1.4.1 at the moment. (https://github.com/pradyunsg/furo/discussions/639)
=> Change: Run workflows with poetry 1.4.0

src/_static/setup-and-start-greenbone-community-edition.sh, src/api.md, src/conf.py, src/glossary.rst, src/history.rst
Changed Greenbone Networks (GmbH) to Greenbone (AG), see https://jira.greenbone.net/browse/DOC-456
=> Changed Greenbone Networks (GmbH) to Greenbone (AG)

src/22.4/source-build/gvm-libs/build.md, src/22.4/source-build/gvmd/dependencies.md, src/22.4/source-build/introduction.md, src/22.4/source-build/openvas-smb.md, src/22.4/source-build/prerequisites.md, src/changelog.md
Change: source code installation for Fedora 38
DEVOPS-717
DEVOPS-717
=> Change: source code installation for Fedora 38

src/faq.md
Add a section about the feed sync scripts to the FAQ
Using the feed sync script may be confusing because of the different available scripts.
https://forum.greenbone.net/t/update-in-progress-for-most-feeds/15066/8
=> Add a section about the feed sync scripts to the FAQ

src/22.4/source-build/index.md, src/changelog.md
Update components to latest releases
Use latest releases of our components for the source build.
=> Change: Update components to latest releases

.github/workflows/auto-merge.yml
Auto-merge workflow, to enable squash auto-merge in open PRs
Save developer time
DEVOPS-804
=> Auto-merge workflow, to enable squash auto-merge in open PRs

src/22.4/source-build/index.md, src/22.4/source-build/workflows.md, src/changelog.md, src/faq.md
Explain how to update to newer releases
Add a new workflow page to explain how to update a source build and mention it in the FAQ. This will provide a single point where users are informed about updating to a newer version. People often ask how to update their community version to the latest release.
=> Add: Explain how to update to newer releases

src/22.4/source-build/workflows.md
Align wording in "Accessing the Web Interface Remotely" chapters
Follow-up of #405 and #404
=> Align wording in "Accessing the Web Interface Remotely" chapters

src/22.4/container/troubleshooting.md, src/22.4/source-build/troubleshooting.md, src/faq.md, src/index.md, src/troubleshooting.md
Add a troubleshooting page for generic issues
Collect generic help for issues popping up more often in the community forum.
=> Generic troubleshooting

src/22.4/container/troubleshooting.md, src/22.4/source-build/troubleshooting.md, src/faq.md, src/troubleshooting.md
Fix some spelling in troubleshooting and FAQ chapters
=> Fix some spelling in troubleshooting and FAQ chapters

.github/PULL_REQUEST_TEMPLATE.md
Use own PR template for docs
Docs don't have tests but require a manual entry in the file.
=> Change: Use own PR template for docs

src/22.4/kali/introduction.md, src/changelog.md
Add a disclaimer for Kali Linux packages
It should be mentioned that Greenbone has no influence in the state of the Kali packages.
=> Add: Add a disclaimer for Kali Linux packages

src/22.4/kali/troubleshooting.md, src/troubleshooting.md
Improve kali troubleshooting
Fix heading levels and link to kali specifc troubleshooting
=> Improve kali troubleshooting

README.md
Update README and add livehtml
Improve the installation procedures in the README and add a section about running a auto-rebuild web server.
=> Change: Update README and add livehtml

src/22.4/container/index.md, src/22.4/container/manual-feed-sync.md, src/22.4/source-build/openvas-scanner/build.md, src/22.4/source-build/openvas-scanner/dependencies.md, src/22.4/source-build/openvasd/build.md, src/22.4/source-build/openvasd/dependencies.md, src/22.4/source-build/openvasd/description.md, src/22.4/source-build/start-services.md, src/22.4/source-build/systemd.md, src/22.4/source-build/workflows.md, src/_static/docker-compose-22.4.yml, src/glossary.md
Update the docs to replace notus-scanner completely and use openvasd instead.
Current the docs are incomplete.
=> Change: Update docs for replacing notus-scanner with openvasd

src/22.4/container/workflows.md
Added TLS_MTA_CERTCHECK to the documentation
https://github.com/greenbone/gvmd/pull/2187/commits/8ca4a773aed1b41a5970c5fd5c34b22c0444427d
=> Added line to workflows to document MTA_TLS_CERTCHECK option

.gitignore, src/_static/custom.css
Fix color of "view this page" icon in dark mode
=> Fix color of "view this page" icon in dark mode

src/_static/custom.css
Change color of visited links from purple to our usual color theme
=> Change color of visited links

src/22.4/source-build/index.md
Update versions of source-build components, see https://jira.greenbone.net/browse/DOC-611
DOC-611
=> Update versions of source-build components

src/_static/docker-compose-22.4.yml
Updated supported images to new registry
[DevOps-1130](https://jira.greenbone.net/browse/DEVOPS-1130)
=> Updated line 62 and 202 with ne registry

src/_static/docker-compose-22.4.yml
Reverts greenbone/docs#499
Does not work without vpn yet
=> Revert "Updated line 62 and 202 with ne registry"

src/_static/docker-compose-22.4.yml
Change: Added registries.
The old registries will soon be outdated, so it will be changed to the new one.
Not all are currently uploaded.
[DEVOPS-1130](https://jira.greenbone.net/browse/DEVOPS-1130)
=> Change: From default dockerhub to community registry

src/faq.md
Change Greenbone Enterprise TRIAL to Greenbone Free, see https://jira.greenbone.net/browse/DOC-647
DOC-647
=> Change Greenbone Enterprise TRIAL to Greenbone Free

src/faq.md
Change link for Greenbone Free, see https://jira.greenbone.net/browse/DOC-647?focusedId=147986&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-147986
DOC-647
=> Change link for Greenbone Free

src/22.4/source-build/openvasd/build.md, src/22.4/source-build/openvasd/description.md, src/changelog.md
Fix the paths to the built openvasd and scannerctl binaries. Also, fix path to openvasd readme.
Close #541 
File paths changed after internal structure changes.
=> Fix: path to the built openvasd and scannerctl binaries

src/_static/docker-compose-22.4.yml
Addressing a tiny grammatical error in `docker-compose-22.4.yml`
It isn't necessary but would read better
N/A
=> Fix grammatical error in sentence about utilizing openvasd directly

.github/workflows/auto-merge.yml
Adjust workflow name to match what it does
The default for auto-merge is rebase, so the name of the workflow should contain this instead of squash
=> Adjust workflow name to match what it does

README.md
Extend README with section about writing content
Explain how the docs are organized.
=> Extend README with section about writing content
