greenbone/docs

- src/common/gsad/build.rst
gsad build with wrong variable [GSA_VERSION](https://github.com/greenbone/docs/blob/c1ac9f51117171a1832db244c5d7906948dea33f/src/common/gsad/build.rst#L6), should be [GSAD_VERSION](https://github.com/greenbone/docs/blob/c1ac9f51117171a1832db244c5d7906948dea33f/src/common/gsad/version.rst#L4)
> fix gsad version variable

- src/common/source-build/gsad/build.rst
**What**:
Fixed typo in gsad/build.rst to note installing gsad not gsa
**Why**:
Typo
**How**:
Fixed typo
**Checklist**:
- [x ] Documentation
> Installing gsad not gsa

- src/21.04/container/index.md
**What**:
When running the containers an admin user has been created already.
Therefore it is only possibly to update the password of the user.
Creating a new admin user will always fail.
**Why**:
Fix updating the password of the admin user
**How**:
**Checklist**:
> Fix command for updating the password of the admin user

- src/_static/docker-compose.yml
**What**:
Until the release is ready and the docs are up to date use oldstable
label for the current docker compose file.
**Why**:
stable (22.04) needs adjustments in the docker compose file.
**How**:
**Checklist**:
> Change: 21.04 is oldstable now

- src/21.4/container/index.md
- src/22.4/container/index.md
- src/_static/setup-and-start-greenbone-community-edition.sh
- src/changelog.md
**What**:
* Support both 21.4 and 22.4 with the script.
* Run the feed sync before starting the services. This avoids issues
with the feed locking when ospd-openvas or gvmd already start loading
the synced files. This could also be something worth for the community
container guide.
**Why**:
Fix using the setup and start script for running the community containers
**How**:
> Fix: Adjust setup and start script for 22.4

- src/21.4/container/index.md
- src/22.4/container/index.md
- src/changelog.md
- src/common/container/feed-loading.md
- src/common/container/feed-sync.md
- src/common/container/performing-feed-sync.md
**What**:
Split feed sync into the download of the data via the sync scripts and
the loading of the data by the daemons. This improves the situation when
ospd-openvas exists while trying to load an incomplete VT sync.
**Why**:
The containers may have issues during startup otherwise (https://community.greenbone.net/t/22-4-docker-ospd-openvas-shut-down/12653)
**How**:
**Checklist**:
> Improve and extend feed sync chapters for community containers

- src/changelog.md
- src/common/source-build/openvas-smb.rst
**What**:
openvas-smb is released independently from the community releases. It is
compatible to both 21.4 and 22.4.
**Why**:
Use latest openvas-smb release.
**How**:
**Checklist**:
> Use latest openvas-smb 22.4.0 release for both community releases

- src/faq.md
**What**:
Fix typo for GVM 10 end of life date
**Why**:
There is no 13th month
**How**:
**Checklist**:
> Fix typo for GVM 10 end of life date

- src/common/container/workflows.md
**What**:
Add: Add section about exposing gvmd unix socket to host
Explain on howto use the GMP protocol over the gvmd unix socket on the
docker host.
**Why**:
Seems to be a feature used by some users.
**How**:
**Checklist**:
> Add: Add section about exposing gvmd unix socket to host

- src/_static/docker-compose-22.4.yml
**What**:
Fix path to the product advisories for notus-scanner container
**Why**:
The path must be `/var/lib/notus/products`.
**How**:
**Checklist**:
> Fix: Fix path to the product advisories for notus-scanner container

- src/21.4/container/index.md
- src/22.4/container/index.md
- src/_static/docker-compose-21.4.yml
- src/_static/docker-compose-22.4.yml
- src/changelog.md
- src/common/container/workflows.md
**What**:
Provde gvm-tools container for 21.4 and 22.4
DEVOPS-347
**Why**:
Allow querying and controlling gvmd and ospd-openvas easily via
gvm-tools CLI.
**How**:
**Checklist**:
> Add: Provde gvm-tools container for 21.4 and 22.4

- src/common/container/prerequisites.md
**What**:
Use same unix command to add current user to the docker group
**Why**:
It seems adduser is Debian specific and to simplify adding the current
user to the docker group use the usermod command for all distributions
instead. This command is available on all distributions.
**How**:
**Checklist**:
> Change: Use same unix command to add current user to the docker group

- src/22.4/source-build/index.rst
- src/changelog.md
**What**:
Use notus-scanner and ospd-openvas 22.4.1
**Why**:
Use newest releases of notus-scanner and ospd-openvas 22.4.1 for 22.4
source build.
**How**:
**Checklist**:
> Change: Use notus-scanner and ospd-openvas 22.4.1

- src/21.4/container/index.md
- src/22.4/container/index.md
- src/_static/setup-and-start-greenbone-community-edition.sh
- src/changelog.md
**What**:
Add the missing executable permission for the downloaded setup and
install script.
**Why**:
Without execute permissions the script can't be run.
**How**:
**Checklist**:
> Fix: Add missing executable permission for setup script

- src/21.4/source-build/systemd.rst
- src/22.4/source-build/systemd.rst
- src/changelog.md
**What**:
It may happen that due to forking the background processes systemd isn't able to track the running processes of gsad. To avoid this situation gsad can be started in foreground.
See https://github.com/greenbone/gsad/pull/84 for some more details.
**Why**:
systemd might not be able to track gsad processes when using forking.
**How**:
**Checklist**:
> Change: Update systemd service file for gsad to start in foreground

- src/_static/docker-compose-21.4.yml
- src/_static/docker-compose-22.4.yml
- src/changelog.md
**What**:
Use docker-init as pid 1 process to prevent nmap, grep zombie processes.
It starts the docker cmd with the docker-init process which handles the zombie process.
**Why**:
After some testing, i saw a lot of zombie nmap zombie process pop up, docker-init process prevent this.
**How**:
**Checklist**:
> Add: docker init process to to prevent nmap, grep zombie processes

- src/_static/docker-compose-21.4.yml
- src/_static/docker-compose-22.4.yml
- src/changelog.md
Add: hostname to ospd-openvas container, to avoid error Could not get a bpf, ethernet address used in non-ether expression
**What**:
**Why**:
Errors like this:
lib  nasl:MESSAGE:2022-10-01 04h17.18 utc:11820: [11820](/var/lib/openvas/plugins/2021/apache/gb_log4j_CVE-2021-44228_tcp_active.nasl:135) pcap_next: Could not get a bpf
lib  misc:MESSAGE:2022-10-01 04h17.18 utc:11820: [gb_log4j_CVE-2021-44228_tcp_active.nasl] pcap_compile: Filter "tcp and dst port 18985 and src host *** and (dst host 172.18.0.7 or dst host c4cc73489cdc)" : ethernet address used in non-ether expression
**How**:
**Checklist**:
> …Add: hostname to ospd-openvas container

- src/_static/custom.css
**What**:
Added background to tabs in light theme. Changed cursor to pointer for tabs.
> Background for tabs in light theme, pointer instead of cursor on tabs

- src/22.4/source-build/notus-scanner/build.rst
- src/common/source-build/gvm-tools/install.rst
- src/common/source-build/ospd-openvas/build.rst
**What**:
Don't use `--prefix` argument with pip for installing ospd-openvas, notus-scanner and gvm-tools.
**Why**:
Using the `--prefix` argument is broken with newer pip versions and at least Python 3.10. The distros are patching CPython's sysconfig module which breaks our expected behavior for the `--prefix` argument. Because the default install prefix is already `/usr/local` we just can remove the `--prefix` argument to circumvent the bug.
See the following links for details:
* https://github.com/pypa/pip/issues/11651
* https://github.com/pypa/pip/issues/10978
* https://discuss.python.org/t/linux-distro-patches-to-sysconfig-are-changing-pip-install-prefix-outside-virtual-environments/18240
**How**:
Tested on a Ubuntu 22.04 container image with packaged Python and pip.
> Change: Don't use `--prefix` argument with pip

- src/changelog.md
- src/common/container/prerequisites.md
**What**:
Update docker compose requirement to 1.29.0
See https://github.com/docker/compose/releases/tag/1.29.0 and https://github.com/docker/compose/issues/8154
Closes #230
**Why**:
The `depends_on` `service_completed_successfully` config in the compose file requires docker compose 1.29.0 actually.
> Change: Update docker compose requirement to 1.29.0

- src/22.4/source-build/notus-scanner/build.rst
- src/changelog.md
- src/common/source-build/ospd-openvas/build.rst
**What**:
Follow up of ff8861133fd173029d6651fdcdb6ecd31159d319 where the `--prefix` argument got removed from the pip install command. It seems that older pip versions behave again differently and use `--user` as default when prefix is missing. Therefore the Python code got installed into `$INSTALL_DIR/home/$USER/.local/lib/python3.X/`. To fix that the `--prefix` argument is introduced again for the older distros.
Background https://forum.greenbone.net/t/notus-installed-to-wrong-location/13767
**Why**:
Fix installation on Debian 11.
> Fix: Fix installing ospd-openvas and notus-scanner on Debian 11

- src/22.4/source-build/mqtt-broker.rst
- src/changelog.md
Set `table_driven_lsc = yes` for openvas-scanner in source build
Enable lsc scanning via notus-scanner.
https://forum.greenbone.net/t/notus-scanner-doesnt-seem-to-be-used-during-scan/13189
> Fix: Set `table_driven_lsc = yes` for openvas-scanner in source build

- src/22.4/source-build/systemd.rst
- src/changelog.md
Update gvmd systemd service file to start gvmd in foreground to avoid
issues with systemd tracking the started processes. It seems that
forking causes a lot of stange issues. For example
Avoid startup issues of gvmd.
https://forum.greenbone.net/t/debian11-gvm-22-4-gvmd-service-cant-open-pid-file-run-gvmd-gvmd-pid-yet-after-start-operation-not-permitted/13886
https://github.com/greenbone/gsad/pull/84
> Change: Use exec mode for gvmd in systemd service file

- src/faq.md
Some minor follow-up updates to #256 including:
- Fix formatting by using bullet points
- Fix outdated GOS 4.x link
- Additional GSM Manual link for Alive Test info
- Update SecInfo links
Some of these changes could be also applied to https://forum.greenbone.net/t/hint-hosts-are-not-scanned-not-shown-as-alive/332 but i'm lacking moderation permission to do so.
The reason to use bullet points can be seen in the screenshot below. The have been rendered one after another which makes them harder to read:
Other changes have been done for consistency reasons or providing more info.
N/A
> Various updates to the FAQ for no scan results

- src/22.4/source-build/systemd.rst
- src/changelog.md
Start mosquitto before ospd-openvas
ospd-openvas depends on mosquitto as a MQTT broker to work correctly. Without being able to communicate with mosquitto ospd-openvas raises errors in the log.
> Fix: Start mosquitto before ospd-openvas

- src/22.4/source-build/index.rst
- src/22.4/source-build/systemd.rst
- src/changelog.md
Run all daemons in exec mode
It seems the forking mode causes issues with systemd for users very often. Therefore run our daemons in foreground and use the systemd exec mode instead.
> Change: Run all daemons in exec mode

- src/22.4/source-build/ospd-openvas/dependencies.rst
- src/changelog.md
Add missing ospd-openvas dependency for gnupg
ospd-openvas uses the python gnupg package for validating the feed data.
> Fix: Add missing ospd-openvas dependency for gnupg

- src/22.4/source-build/verify.rst
- src/changelog.md
- src/conf.py
Allow to disable copy and paste button for code highlight
Don't display copy and paste for the gpg signature verification output.
https://sphinx-copybutton.readthedocs.io/en/latest/use.html#remove-copybuttons-using-a-css-selector
> Change: Allow to disable copy and paste button for code highlight

- src/22.4/source-build/gvm-tools/dependencies.rst
- src/22.4/source-build/gvm-tools/install.rst
- src/22.4/source-build/notus-scanner/build.rst
- src/22.4/source-build/notus-scanner/dependencies.rst
- src/22.4/source-build/ospd-openvas/build.rst
- src/22.4/source-build/ospd-openvas/dependencies.rst
- src/22.4/source-build/prerequisites.rst
- src/changelog.md
Improve python software installations
Installing with pip using `--prefix` and `--root` is an unreliable mess because distributions are patching the system Python. Therefore use a virtual environment which avoids the patches.
> Improve python software installations

- src/22.4/source-build/postgres.rst
- src/changelog.md
Fix copy and paste for postgres setup
Copy and pasting the commands wasn't possible and resulted in a broken environment for the user. Therefore fix the postgres setup by allowing to copy and paste the commands again.
Should be merged after #265
> Fix: Fix copy and paste for postgres setup

- src/22.4/source-build/index.rst
- src/changelog.md
Use new releases of ospd-openvas, notus-scanner and gvm-libs from today.
ospd-openvas and notus-scanner also log to their logging files if they are running in foreground now.
> Change: Update to new releases

- src/22.4/source-build/notus-scanner/dependencies.rst
- src/22.4/source-build/ospd-openvas/dependencies.rst
Use same dependencies for Ubuntu and Debian for scanners
Ubuntu and Debian need the same Python dependencies for notus-scanner and ospd-openvas. Therefore merge these tabs. Also remove settings the INSTALL_PREFIX unnecessarily.
Setting the INSTALL_PREFIX is just wrong here.
https://forum.greenbone.net/t/install-prefix-change-not-reflected-in-systemd-scripts/14043
> Change: Use same dependencies for Ubuntu and Debian for scanners

- src/architecture.rst
- src/changelog.md
Remove 21.4 from the architecture docs
21.4 is end of life and not supported anymore.
> Change: Remove 21.4 from the architecture docs

- src/22.4/source-build/greenbone-feed-sync/dependencies.rst
- src/22.4/source-build/greenbone-feed-sync/install.rst
- src/22.4/source-build/gvm-tools/install.rst
- src/22.4/source-build/notus-scanner/build.rst
- src/22.4/source-build/notus-scanner/dependencies.rst
- src/22.4/source-build/ospd-openvas/build.rst
- src/22.4/source-build/ospd-openvas/dependencies.rst
- src/22.4/source-build/prerequisites.rst
- src/changelog.md
Try to fix installation of Python based applications again
Revert using the virtual environments for installing our Python based applications because that used an absolute to the Python executable of the venv in all installed scripts which of course doesn't work at the end.
Using venv doesn't work.
https://forum.greenbone.net/t/build-from-source-url-not-found/14081/4
https://discuss.python.org/t/linux-distro-patches-to-sysconfig-are-changing-pip-install-prefix-outside-virtual-environments/18240
> Change: Try to fix installation of Python based applications again

- src/22.4/source-build/prerequisites.rst
- src/changelog.md
Switch setting install prefix and path sections
Switch *Choosing an Install Prefix* and *Setting the PATH* section in source build to allow using $INSTALL_PREFIX when setting the $PATH.
> Change: Switch setting install prefix and path sections

- src/22.4/source-build/index.rst
- src/changelog.md
Update to notus-scanner 22.4.5
notus-scanner got a new release to fix RPM package comparisons with epochs.
https://github.com/greenbone/notus-scanner/pull/453
> Change: Update to notus-scanner 22.4.5

- src/22.4/source-build/postgres.md
- src/changelog.md
Avoid permission errors when setting up postgres db
Depending on the default settings for creating a user the current working directory may not be executable and readable for the postgres user. When running the commands for setting up the postgres database in this home directory permission errors may be raised. To avoid that change into the home directory of the postgres user before setting up the database.
> Fix: Avoid permission errors when setting up postgres db

- src/glossary.md
Adding the description for NASL based on the existing docs from scanner team side available at https://github.com/greenbone/openvas-scanner/blob/main/doc/manual/nasl/index.md
Note: If there are remarks (e.g. not sure about the `OpenVAS project` used in the existing docs) it should be aligned with the suggested changes in greenbone/openvas-scanner#1432
The current glossary contained a reference to `NASL` but didn't described what `NASL` actually is.
N/A
> Add: Description for NASL to Glossary

- src/22.4/source-build/greenbone-feed-sync/dependencies.md
- src/22.4/source-build/gvm-tools/dependencies.md
- src/22.4/source-build/redis.md
Fixing missing `sudo` on two rpm install commands and also fixing `sudo` permission error on chained commands.
Some CentOS source code install commands fail due to permission errors because sudo is not passed to chained commands appropriately.
None
- [ *] I tested these changes on CentOS stream 9
> Fixing some failed commands for CentOS source code install

- src/22.4/container/introduction.md
- src/glossary.md
Use *pre-built* as the container images are built in advance.
> Fix spelling of 'pre-built'

- src/22.4/source-build/gsad/version.md
- src/22.4/source-build/index.md
- src/22.4/source-build/pg-gvm/build.md
- src/changelog.md
Update pg-gvm to 22.5.1 and gsad to 22.5.0 release
Use newest releases of pg-gvm and gsad. pg-gvm 22.5.1 will find postgres 14 and 15 too.
> Change: Update pg-gvm to 22.5.1 and gsad to 22.5.0 releases

- src/22.4/container/workflows.md
This PR adds the documentation block on configuration of mail transport agent, which is going to be added with `gvmd` PR #2046 and will provide functionality of sending emails.
It is documentation for new feature. 
[`gvmd` PR #2046](https://github.com/greenbone/gvmd/pull/2046)
> Add: Documentation for PR #2046 (mail transport agent)

- src/22.4/source-build/index.md
- src/changelog.md
Update gvmd, gsa and openvas-scanner versions
Use the newest releases in the source build guide.
> Change: Update gvmd, gsa and openvas-scanner versions

- src/22.4/container/admin-user.md
- src/22.4/container/manual-feed-sync.md
- src/22.4/container/prerequisites.md
- src/22.4/container/starting.md
- src/22.4/container/troubleshooting.md
- src/22.4/container/workflows.md
- src/_static/setup-and-start-greenbone-community-edition.sh
- src/changelog.md
This PR updated the documentation to use the official Docker repo instead of the Debian / Ubuntu one to install the Docker packages.
It's mainly for docker-compose to use the latest release instead of the EOL Debian / Ubuntu package or the one from PyPi. Compose is now installed as a CLI plugin with version 2 instead of a standalone binary in version 1.
`The final Compose V1 release, version 1.29.2, was May 10, 2021. These packages haven't received any security updates since then. Use at your own risk.` (from https://docs.docker.com/compose/migrate/).
Both the Debian / Ubuntu package and the PyPi package contain Compose v1, which we shouldn't recommend using any more (Note: Compose v2 will be available for the upcoming Ubuntu 23.10 as `docker-compose-v2`).
I adapted the Docker install …
> Use official Docker repository and install Compose v2

- src/faq.md
See title. Note that i'm not 100% sure about the terms / syntax and if the links to the EOL notice is even required.
Don't list EOL software / versions as still supported.
None
> Change: Mark 21.4 releases as EOL in FAQ

- poetry.lock
Bump `furo` separately to disentangle it from the conflict between `pyparsing` and `matplotlib` in the grouped updates pull request #385.
> Update 'furo' dependency separately

- src/22.4/source-build/index.md
- src/changelog.md
Update GSA to the 22.7.1 release
Use the newest GSA release in source build to include some bug fixes.
> Change: Update GSA to the 22.7.1 release

- src/_static/docker-compose-22.4.yml
Don't expose MQTT broker on all host interfaces
This was added mostly for testing purposes and is not required for running the community edition. Because the MQTT broker doesn't use authentication this could even be a security risk when using the docker container in some productive environment.
Fixes #366
> Change: Don't expose MQTT broker on all host interfaces

- src/22.4/source-build/workflows.md
- src/changelog.md
Add workflow for source build to allow remote access to gsa(d)
Add workflow on how to change the systemd service file to allow gsad listen on all local network interfaces and not only on localhost. This will allow to access GSA remotely from a different machine.
> Add: Add workflow for source build to allow remote access to gsa(d)

- src/22.4/container/workflows.md
- src/_static/docker-compose-22.4.yml
- src/changelog.md
Don't listen on all docker host addresses for gsad
For security reasons only expose gsad on the localhost address of the docker host when using the container setup.
#398
> Change: Don't listen on all docker host addresses for gsad

- src/_static/docker-compose-22.4.yml
- src/changelog.md
Fix log warning caused by tini init server in ospd-openvas container
Remove warning message from the docker compose log output to not confuse users. It worked as it should nevertheless.
> Fix log warning caused by tini init server in ospd-openvas container

- src/22.4/container/manual-feed-sync.md
- src/22.4/container/workflows.md
- src/changelog.md
Adjust container workflow for manual feed sync
After fixing the permissions in the feed data container images it's finally possible to run a manual feed sync again. Therefore fix and update the container workflow for doing a manual feed sync using the `greenbone-feed-sync` script.
#367
> Fix: Adjust container workflow for manual feed sync

- src/22.4/source-build/index.md
- src/changelog.md
Update gvm-libs, gvmd, gsad and GSA to latest releases
Use latest releases for gvm-libs, gvmd, gsad and GSA for the source build guide.
> Change: Update gvm-libs, gvmd, gsad and GSA to latest releases

- src/conf.py
- Update copyright for 2024
- Change colors to those from https://confluence.greenbone.net/display/MAR/Color+palette+for+designers+and+developers+-+extended+use (although I'm not sure if they are actually used)
> Update copyright for 2024

- src/22.4/container/workflows.md
- src/changelog.md
Instructions for SSL/TLS configuration for GSA have been added to the `22.4/container/workflows.md` file.
Common question on the forum
- [ *] Compiled with Sphinx and myst 
- [ *] Verified the contents as HTML
> Instructions for SSL/TLS configuration for GSA

- src/22.4/container/admin-user.md
- src/22.4/source-build/admin-user.md
- src/changelog.md
Quote passwords when creating an admin user
If the password isn't quoted via single quotes it will interpreted by the shell and therefore characters like `$` have special meanings.
https://forum.greenbone.net/t/cannot-change-admin-password/16575
> Change: Quote passwords when creating an admin user

- src/22.4/kali/index.md
- src/22.4/kali/troubleshooting.md
- src/22.4/source-build/index.md
* Rearrange order of workflow and troubleshooting chapters for source build
* Extract troubleshooting for kali into an own chapter
* Strip unnecessary white space
Get a consistent page layout for troubleshooting chapters
> Consistent troubleshooting chapters

- src/troubleshooting.md
See commit title
- NASL is not C so you can't introduce any memory leaks or similar
- Any memory issue needs to be either fixed on scanner side (e.g. memory leaks, better memory management, ...) or solved via changes to the scan config (by e.g. the ones outlined in the parts above or by limit the concurrent scanned hosts and similar)
- Pointing users to the vulnerability tests category won't help as these things can't be fixed/solved on VT side
None
> Change: Replace ref to VTs category with better fitting scan config one

- src/22.4/source-build/troubleshooting.md
- src/changelog.md
- src/troubleshooting.md
Add hints for handling errors to generic troubleshooting page
The hints on the source build guide are valid for all variants of our software (maybe only partly for the containers but nevertheless).
Allow to point users to this description for many topics in the community forum.
For example https://forum.greenbone.net/t/unable-to-install-openvas-in-virtualbox/16593
> Change: Add hints for handling errors to generic troubleshooting page

- src/22.4/container/preamble.md
- src/22.4/source-build/index.md
- src/changelog.md
Update component versions to latest releases for source build
Use the newest component releases for building from sources.
> Updated releases

- src/22.4/container/troubleshooting.md
- src/changelog.md
Add a section on how to access the logs of the community containers
Not all people using our containers seem to be familiar with `docker` and `docker compose` and therefore might not know how to get access to the log messages. Therefore explain in detail how to get log messages from our software stack when
running the community containers.
https://forum.greenbone.net/t/how-to-move-docker-based-installation-to-other-host/16716/3
> Add: Add a section on how to access the logs of the community containers

- README.md
Update README regarding installation and updates
For Python devs familiar with poetry these steps are mostly obvious. But this is not the case for new or outside contributors.
> Change: Update README regarding installation and updates

- README.md
- pyproject.toml
Require poetry 1.8.0 to use non package mode 
In the non package mode poetry can be used to maintain projects not
intended for publishing a python package on pypi. This is exactly the
use case for our docs project. We are just using poetry for maintaining
and installing the dependencies.
> Change python project setup

- src/22.4/source-build/feed-loading.md
- src/22.4/source-build/troubleshooting.md
- src/changelog.md
Improve troubleshooting of failed of failed to find port list
Mention the log message when gvmd indicated it actually has loaded the port list from the feed.
https://forum.greenbone.net/t/failed-to-find-port-list-33d0cd82-57c6-11e1-8ed1-406186ea4fc5/16925
> Add: Improve troubleshooting of failed of failed to find port list

- src/22.4/container/index.md
- src/22.4/source-build/index.md
- src/index.md
Make the release version less visible
We only have a single maintained release which was known as 22.4. Since this release nearly all our software components switched to semver instead of calver and are released independently now. Thus showing 22.4 can be confusing when gvmd, openvas-scanner and other components are at 23.x.y. Also we are already in the year 22.4 which gives the impression our software may be already two years old without further releases.
> Change: Make the release version less visible

- src/history.md
- src/index.md
Drop term Greenbone OpenVAS and just use OpenVAS
It's better to just mention OpenVAS as a former name of Greenbone Community Edition.
> Change: Drop term Greenbone OpenVAS and just use OpenVAS

- src/22.4/container/manual-feed-sync.md
- src/changelog.md
Fix compose command for downloading gvmd data manually
The greenbone-feed-sync application must be run within a greenbone-feed-sync container. Otherwise it wont be available.
https://forum.greenbone.net/t/error-exec-greenbone-feed-sync-executable-file-not-found-in-path/17082/8
> Fix compose command for downloading gvmd data manually

- src/_static/docker-compose-22.4.yml
When executing docker-compose on some systems:
```
Can not open or create log file or directory. Please check permissions of log files listed in /etc/openvas/openvas_log.con
```
occurs. To fix that we create a openvas.log upfront with the
persmissions `666`.
> Fix: can not open or create log file

- src/22.4/source-build/openvasd/build.md
Fixed export variable for the path name for OpenVasd.
Fixing OpenVasd Build documentation
It needs correct export variable to change to the correct directory
> OpenVasd Build Documation

- src/22.4/kali/optional-configs.md
A small change to fix a typo in the path of gsad.service file and include the additional steps to restart the gsad.service after changes.
I found a typo on the path of the gsad.service file and added some more complete instructions.
> Small change to configuring gsad.service for remote access

- src/22.4/source-build/openvasd/build.md
- src/changelog.md
Openvasd: fix incorrect install path when moving files to final destination
https://forum.greenbone.net/t/missing-content-after-installation-according-to-files/17931/2
- [* ] [Changelog](src/changelog.md) entry
> Openvasd: fix incorrect install path when moving files to final destination

- src/_static/docker-compose-22.4.yml
This PR fixes a typo preventing the `openvasd` to start.
To allow `openvasd` to correctly start in `service_notus` mode.
This has been introduced in https://github.com/greenbone/docs/pull/459.
> Fix: Typo in environment variable and comment

- src/22.4/source-build/index.md
Update version of ospd-openvas to 22.7.1 and openvas-scanner to 23.8.0
- Closes #492 
- Could also replace / make #475 void
> Change: Update versions of ospd-openvas and openvas-scanner

- src/22.4/source-build/openvas-scanner/build.md
no need to sudo before tee
remove sudo command before tee
adding sudo everywhere is bad practice. This line isn't consistent with the rest of the documentation
-
- [ N ] [Changelog](src/changelog.md) entry
> Fix: Remove not required `sudo` from documentation

- src/22.4/container/admin-user.md
- src/22.4/container/docker-compose.yml
- src/22.4/container/index.md
- src/22.4/container/manual-feed-sync.md
- src/22.4/container/preamble.md
- src/22.4/container/starting.md
- src/22.4/container/troubleshooting.md
- src/22.4/container/workflows.md
- src/_static/docker-compose-22.4.yml
- src/_static/setup-and-start-greenbone-community-edition.sh
- src/changelog.md
* use `docker-compose.yml` for download instead of versioned file
* set project already in compose file
* update supported ubuntu version for compose setup
Get an up to date compose setup easier to handle
> Improve compose file

- src/22.4/source-build/index.md
- src/22.4/source-build/openvas-scanner/dependencies.md
- src/22.4/source-build/openvas-smb.md
- src/changelog.md
Doc: add krb5-dev openvas dependency
Doc: remove fedora from openvas-smb as it does not build anymore.
Close greenbone/openvas-scanner#1803
missing dependency in openvas-scanner install documentation
> Doc: add krb5-dev openvas dependency

- src/_static/docker-compose-22.4.yml
- src/changelog.md
Update compose file to use 24.10 feed release
Use the correct feed for gvmd 25.0.0.
https://jira.greenbone.net/browse/GEA-905
> Update compose file to use 24.10 feed release

- src/_static/docker-compose-22.4.yml
Fix setting the FEED_RELEASE in compose file
Unquoted values in YAML (and also JSON) files are considered as numbers and therefore the trailing zero is cut from the feed release environment variable. To fix this the FEED_RELEASE value needs to be quoted.
https://github.com/greenbone/docs/commit/f5e6adfff52be5b76b0b5c49b854e5caf7bc5d63#commitcomment-152409226
https://forum.greenbone.net/t/vulnerability-tests-service-fails-to-start-on-new-docker-install/20397
Closes https://github.com/greenbone/docs/issues/549
> Fix setting the FEED_RELEASE in compose file

- src/_static/setup-and-start-greenbone-community-edition.sh
By quoting variables we can improve stability of this script. $HOME and $password are both user supplied variables, that may contain spaces.
We need to quote them, or they may be expanded into extra arguments. This means this scripit will no longer break, if a space is supplied inside the password.
In tests it was discovered that setup sometime fails. This turned out due to passwords that contain spaces, breaking the setup script.
This PR tries to fix this problem, and mitigates a couple of other potential issues.
Currently the problem still persists. I suspect that the same problem also happens inside the container entrypoint, and needs to be quoted there as well. Until then this PR will remain a **draft**.
Variables should be quoted if they may contain spaces (`$password`, …
> Quote variables for well defined behavior

- src/22.4/source-build/gvmd/dependencies.md
- src/changelog.md
From https://packages.debian.org/bookworm/lcov:
> Summarise Code coverage information from GCOV
>
> LCOV is an extension of GCOV, a GNU tool which provides information about what parts of a program are actually executed (i.e. "covered") while running a particular test case.
Installing this development dependency would install a huge amount of unnecessary dependencies (currently for my Debian testing system, might be even more on other "more clean" systems):
```
Summary:
Upgrading: 0, Installing: 53, Removing: 0, Not Upgrading: 0
Download size: 5.057 kB
Space needed: 38,1 MB / 2.276 MB available
```
but none of the `gvmd` docs indicates that this is required / mandatory:
https://github.com/search?q=repo%3Agreenbone%2Fgvmd%20lcov&type=code
Could be even possible to drop the remaining parts …
> Remove: Drop `lcov` development dependency in gvmd install instructions

- src/22.4/source-build/prerequisites.md
- src/22.4/source-build/troubleshooting.md
- src/22.4/source-build/workflows.md
- src/changelog.md
Put setting environment variables into an own section
Allow for better linking to a section setting all required env vars. Also explain the issues with environment variables being only valid in the current shell.
> Change: Put setting environment variables into an own section

- src/22.4/source-build/gvm-libs/download.md
Related to issue #564
In section “Downloading the gvm-libs sources”, the below address in wrong.
curl -f -L https://github.com/greenbone/gvm-libs/releases/download/v$GVM_LIBS_VERSION/gvm-libs-v$GVM_LIBS_VERSION.tar.gz.asc -o $SOURCE_DIR/gvm-libs-$GVM_LIBS_VERSION.tar.gz.asc
the part “gvm-libs-v$GVM_LIBS_VERSION.tar.gz.asc” has one extra “v” that is not needed.
The correct address is:
curl -f -L https://github.com/greenbone/gvm-libs/releases/download/v$GVM_LIBS_VERSION/gvm-libs-$GVM_LIBS_VERSION.tar.gz.asc -o $SOURCE_DIR/gvm-libs-$GVM_LIBS_VERSION.tar.gz.asc
> corrected address for gvm-libs asc

- README.md
- src/22.4/source-build/index.md
- src/changelog.md
Update components to their latest releases
Users should build latest versions of our software stack.
> Update components to their latest releases

- src/22.4/source-build/openvasd/dependencies.md
- src/22.4/source-build/openvasd/description.md
- src/changelog.md
Improve hints for installing cargo on Debian and CentOS
On both distros the rust toolchain is too old for building openvasd. Therefore the users need to install it via rustup.sh.
> Improve hints for installing cargo on Debian and CentOS

- src/22.4/source-build/openvasd/dependencies.md
- src/changelog.md
Ensure cargo is always up-to-date for openvasd
Distributions may ship with an too old cargo version for openvasd. Therefore update cargo to the latest stable version via rustup.
https://forum.greenbone.net/t/openvasd-build-fails/21340/6
> Ensure cargo is always up-to-date for openvasd
